export default{
    products:[
        {
            id:'1',
            name:'Slim-Shirt',
            img:'/img/p1.jpeg',
            brand:'Nike',
            price:450,
            reveiw:'2 Reveiws',
            rating:4,
            category:'shirt',
            countInStock: 0,
        },
        {
            id:'2',
            name:'Jeans Pant',
            img:'/img/p1.jpeg',
            brand:'Max',
            price:1050,
            reveiw:'3 Reveiws',
            rating:4,
            category:'pant',
            countInStock: 1,
        },
        {
            id:'3',
            name:'T-Shirt',
            img:'/img/p1.jpeg',
            brand:'LP',
            price:850,
            reveiw:'2 Reveiws',
            rating:3,
            category:'shirt',
            countInStock: 2,
        },
        {
            id:'4',
            name:'k-Shirt',
            img:'/img/p1.jpeg',
            brand:'PP',
            price:850,
            reveiw:'2 Reveiws',
            rating:3,
            category:'shirt',
            countInStock: 5,
        },
        {
            id:'5',
            name:'T-Shirt',
            img:'/img/p1.jpeg',
            brand:'LP',
            price:850,
            reveiw:'2 Reveiws',
            rating:3,
            category:'shirt',
            countInStock: 3,
        },
    ]
}